import assert from 'node:assert/strict';
import jpeg from 'jpeg-js';
import type { ScanSession, Spread } from '../lib/types';

process.loadEnvFile('.dev.vars');
const base = process.env.TEST_URL || process.env.PROCESSOR_BASE_URL!;
const session = process.argv[2];
if (!session) throw new Error('Supply an existing, fully processed test session.');
const request = (path: string, extra?: HeadersInit) => {
  const headers = new Headers(extra);
  if (new URL(base).hostname.endsWith('.chatgpt.site')) headers.set('OAI-Sites-Authorization', `Bearer ${process.env.SITE_ACCESS_TOKEN}`);
  return fetch(base+path,{headers});
};
const root = `/api/sessions/${session}`;
const fullResponse = await request(root);
assert.equal(fullResponse.status,200);
const fullText = await fullResponse.text();
const full = JSON.parse(fullText) as ScanSession;
assert.ok(full.spreads.length > 0);
const summaryResponse = await request(root+'?summary=1');
assert.equal(summaryResponse.status,200);
const summaryText = await summaryResponse.text();
const summary = JSON.parse(summaryText) as ScanSession;
assert.deepEqual(summary.spreads.map((s)=>s.id),full.spreads.map((s)=>s.id));
assert.ok(summary.spreads.every((s)=>!s.spans && !s.annotations));
assert.ok(summaryText.length < fullText.length);
const unchanged = await request(root+'?summary=1',{'If-None-Match':summaryResponse.headers.get('etag')!});
assert.equal(unchanged.status,304);
assert.equal((await unchanged.text()).length,0);
const capture = full.spreads[0];
const path = `${root}/spreads/${capture.id}`;
const detailResponse = await request(path);
assert.equal(detailResponse.status,200);
const detail = await detailResponse.json() as Spread;
assert.deepEqual(detail.spans,capture.spans);
assert.deepEqual(detail.annotations,capture.annotations);
assert.equal((await request(path,{'If-None-Match':detailResponse.headers.get('etag')!})).status,304);
const originalResponse = await request(path+'/image/original');
assert.equal(originalResponse.status,200);
const originalBytes = (await originalResponse.arrayBuffer()).byteLength;
const thumbResponse = await request(path+'/image/thumbnail');
assert.equal(thumbResponse.status,200);
const thumb = new Uint8Array(await thumbResponse.arrayBuffer());
const dimensions = jpeg.decode(thumb,{useTArray:true});
assert.ok(Math.max(dimensions.width,dimensions.height)<=280);
assert.ok(thumb.byteLength < originalBytes / 5);
assert.equal((await request(path+'/image/thumbnail',{'If-None-Match':thumbResponse.headers.get('etag')!})).status,304);
console.log(`PASS: ${full.spreads.length} real captures; list ${Buffer.byteLength(fullText)} → ${Buffer.byteLength(summaryText)} bytes; unchanged 304/0 bytes; detail exact; thumbnail ${originalBytes} → ${thumb.byteLength} bytes (${dimensions.width}×${dimensions.height}).`);
